language: java
jdk:
- openjdk14
env:
  - TRAVIS_NODE_VERSION="8"
before_install:
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.10.7-bin.tar.gz
  - tar xvfvz apache-ant-1.10.7-bin.tar.gz
  - sudo mv apache-ant-1.10.7 /opt/ant
  - sudo sh -c 'echo ANT_HOME=/opt/ant >> /etc/environment'
  - sudo ln -s /opt/ant/apache-ant-1.10.7/bin/ant /usr/bin/ant -f
install:
  - sudo apt-get install -y ant ant-option
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
script: 
  - export JAVA_HOME=~/openjdk14
  - export JDK_HOME=~/openjdk14
  - export PATH=${PATH}:${ANT_HOME}/bin
  - set
  - ant -diagnostics
  - ant all
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  local_dir: javadoc
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  keep_history: true
  on:
    branch: master
